/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Libreria;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        actualizarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan_principal = new javax.swing.JPanel();
        jBut_salir = new javax.swing.JButton();
        jLbl_icono = new javax.swing.JLabel();
        jCB_usuarios = new javax.swing.JComboBox<>();
        jLbl_usuario = new javax.swing.JLabel();
        jLbl_pass = new javax.swing.JLabel();
        jPass_pass = new javax.swing.JPasswordField();
        jBut_login = new javax.swing.JButton();
        jLbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 450));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        jPan_principal.setLayout(null);

        jBut_salir.setBackground(new java.awt.Color(255, 0, 0));
        jBut_salir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBut_salir.setForeground(new java.awt.Color(0, 0, 0));
        jBut_salir.setText("Salir");
        jBut_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 51), new java.awt.Color(255, 153, 153), null, null));
        jBut_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_salirActionPerformed(evt);
            }
        });
        jPan_principal.add(jBut_salir);
        jBut_salir.setBounds(475, 20, 90, 22);

        jLbl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-usuario.png"))); // NOI18N
        jPan_principal.add(jLbl_icono);
        jLbl_icono.setBounds(200, 50, 200, 200);

        jPan_principal.add(jCB_usuarios);
        jCB_usuarios.setBounds(260, 270, 210, 30);

        jLbl_usuario.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_usuario.setText("Usuario:");
        jPan_principal.add(jLbl_usuario);
        jLbl_usuario.setBounds(150, 270, 50, 30);

        jLbl_pass.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_pass.setText("Contraseña:");
        jPan_principal.add(jLbl_pass);
        jLbl_pass.setBounds(150, 320, 80, 30);

        jPass_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPass_passActionPerformed(evt);
            }
        });
        jPass_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPass_passKeyPressed(evt);
            }
        });
        jPan_principal.add(jPass_pass);
        jPass_pass.setBounds(260, 320, 210, 30);

        jBut_login.setBackground(new java.awt.Color(0, 0, 255));
        jBut_login.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBut_login.setForeground(new java.awt.Color(204, 255, 255));
        jBut_login.setText("Entrar");
        jBut_login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), null, null));
        jBut_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_loginActionPerformed(evt);
            }
        });
        jPan_principal.add(jBut_login);
        jBut_login.setBounds(250, 380, 120, 30);

        jLbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-login.png"))); // NOI18N
        jPan_principal.add(jLbl_fondo);
        jLbl_fondo.setBounds(0, 0, 600, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBut_salirActionPerformed

    private void jPass_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPass_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPass_passActionPerformed

    private void jBut_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_loginActionPerformed
        entrar();

    }//GEN-LAST:event_jBut_loginActionPerformed

    private void jPass_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPass_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrar();
        }
    }//GEN-LAST:event_jPass_passKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_login;
    private javax.swing.JButton jBut_salir;
    private javax.swing.JComboBox<String> jCB_usuarios;
    private javax.swing.JLabel jLbl_fondo;
    private javax.swing.JLabel jLbl_icono;
    private javax.swing.JLabel jLbl_pass;
    private javax.swing.JLabel jLbl_usuario;
    private javax.swing.JPanel jPan_principal;
    private javax.swing.JPasswordField jPass_pass;
    // End of variables declaration//GEN-END:variables

    private void actualizarUsuarios() {
        ArrayList<Libreria> lista = new Controlador.LibreriaDAOImpl().listarTodos();
        for (Libreria aux : lista) {
            jCB_usuarios.addItem(aux.toString());
        }
    }

    private void entrar() {
        Libreria lib = (Libreria) new Controlador.LibreriaDAOImpl().leer(jCB_usuarios.getSelectedItem().toString());
        if (lib != null) {
            if (jPass_pass.getText().equals(lib.getClave())) {
                Controlador.GestionLibreria.idUsuario = lib.getId();
                new VistaPrincipal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "La contraseña ingresada no coincide con el usuario");
            }
        }
    }
}
