/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO.LibroDAOImpl;
import Controlador.TxtMayusculas;
import Modelo.Escritor;
import Modelo.Genero;
import Modelo.Libro;
import Modelo.SelloEditorial;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class NuevoLibro extends javax.swing.JFrame {

    /**
     * Creates new form NuevoLbro
     */
    public NuevoLibro() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        TxtMayusculas.soloMayus(jTxt_Titulo);
        limpiarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan_General = new javax.swing.JPanel();
        jBtn_Volver = new javax.swing.JButton();
        jLbl_NvLibro = new javax.swing.JLabel();
        jPan_Datos = new javax.swing.JPanel();
        jLbl_Titulo = new javax.swing.JLabel();
        jTxt_Titulo = new javax.swing.JTextField();
        jLbl_Precio = new javax.swing.JLabel();
        jLbl_Genero = new javax.swing.JLabel();
        jBtn_BuscarGenero = new javax.swing.JButton();
        jlbl_GeneroSeleccionado = new javax.swing.JLabel();
        jLbl_AutorSeleccionado = new javax.swing.JLabel();
        jLbl_Autor = new javax.swing.JLabel();
        jBtn_BuscarAutor = new javax.swing.JButton();
        jLbl_EditorialSeleccionada = new javax.swing.JLabel();
        jLnl_Editorial = new javax.swing.JLabel();
        jBtn_BuscarEditorial = new javax.swing.JButton();
        jTxt_Precio = new javax.swing.JTextField();
        jLbl_ISBN = new javax.swing.JLabel();
        jTxt_ISBN = new javax.swing.JTextField();
        jBtn_Cargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 650));
        setMinimumSize(new java.awt.Dimension(600, 650));
        setUndecorated(true);
        setResizable(false);

        jPan_General.setBackground(new java.awt.Color(204, 255, 204));
        jPan_General.setMaximumSize(new java.awt.Dimension(600, 650));
        jPan_General.setMinimumSize(new java.awt.Dimension(600, 650));

        jBtn_Volver.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtn_Volver.setText("Volver");
        jBtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VolverActionPerformed(evt);
            }
        });

        jLbl_NvLibro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLbl_NvLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_NvLibro.setText("Nuevo Libro");

        jLbl_Titulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Titulo.setText("Titulo:");

        jTxt_Titulo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTxt_Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_TituloActionPerformed(evt);
            }
        });

        jLbl_Precio.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Precio.setText("Precio:");

        jLbl_Genero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Genero.setText("Genero:");

        jBtn_BuscarGenero.setText("...");
        jBtn_BuscarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BuscarGeneroActionPerformed(evt);
            }
        });

        jlbl_GeneroSeleccionado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jlbl_GeneroSeleccionado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbl_AutorSeleccionado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_AutorSeleccionado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbl_Autor.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Autor.setText("Autor:");

        jBtn_BuscarAutor.setText("...");
        jBtn_BuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BuscarAutorActionPerformed(evt);
            }
        });

        jLbl_EditorialSeleccionada.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_EditorialSeleccionada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLnl_Editorial.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLnl_Editorial.setText("Editorial:");

        jBtn_BuscarEditorial.setText("...");
        jBtn_BuscarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BuscarEditorialActionPerformed(evt);
            }
        });

        jTxt_Precio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTxt_Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_PrecioActionPerformed(evt);
            }
        });

        jLbl_ISBN.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_ISBN.setText("ISBN:");

        jTxt_ISBN.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTxt_ISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ISBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPan_DatosLayout = new javax.swing.GroupLayout(jPan_Datos);
        jPan_Datos.setLayout(jPan_DatosLayout);
        jPan_DatosLayout.setHorizontalGroup(
            jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_DatosLayout.createSequentialGroup()
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPan_DatosLayout.createSequentialGroup()
                        .addComponent(jLbl_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jTxt_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLbl_EditorialSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPan_DatosLayout.createSequentialGroup()
                            .addComponent(jLnl_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jBtn_BuscarEditorial)))
                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLbl_AutorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPan_DatosLayout.createSequentialGroup()
                            .addComponent(jLbl_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jBtn_BuscarAutor)))
                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPan_DatosLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jlbl_GeneroSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPan_DatosLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPan_DatosLayout.createSequentialGroup()
                                    .addComponent(jLbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)
                                    .addComponent(jTxt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPan_DatosLayout.createSequentialGroup()
                                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLbl_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLbl_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPan_DatosLayout.createSequentialGroup()
                                            .addGap(52, 52, 52)
                                            .addComponent(jTxt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPan_DatosLayout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jBtn_BuscarGenero))))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPan_DatosLayout.setVerticalGroup(
            jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_DatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPan_DatosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLbl_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_BuscarGenero))
                .addGap(18, 18, 18)
                .addComponent(jlbl_GeneroSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_BuscarAutor))
                .addGap(18, 18, 18)
                .addComponent(jLbl_AutorSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnl_Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_BuscarEditorial))
                .addGap(18, 18, 18)
                .addComponent(jLbl_EditorialSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtn_Cargar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBtn_Cargar.setText("Cargar");
        jBtn_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPan_GeneralLayout = new javax.swing.GroupLayout(jPan_General);
        jPan_General.setLayout(jPan_GeneralLayout);
        jPan_GeneralLayout.setHorizontalGroup(
            jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan_GeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Volver)
                .addGap(47, 47, 47))
            .addGroup(jPan_GeneralLayout.createSequentialGroup()
                .addGroup(jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPan_GeneralLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLbl_NvLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPan_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPan_GeneralLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jBtn_Cargar)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPan_GeneralLayout.setVerticalGroup(
            jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_GeneralLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBtn_Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbl_NvLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPan_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Cargar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_TituloActionPerformed

    private void jTxt_PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_PrecioActionPerformed

    private void jBtn_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CargarActionPerformed
        if (sello!=null && autor!= null && genero != null && !jTxt_Precio.getText().equals("") && !jTxt_Titulo.getText().equals("") && !jTxt_ISBN.getText().equals("") ) {
            Libro nuevoLibro = new Libro (jTxt_ISBN.getText()
                    , Double.parseDouble(jTxt_Precio.getText()),
                    jTxt_Titulo.getText(), autor, genero, sello);
            if (new LibroDAOImpl().agregar(nuevoLibro)) {
                JOptionPane.showMessageDialog(this, "Libro cargado con exito");
                limpiarDatos();
            }else{
                 JOptionPane.showMessageDialog(this,  "Error al cargar",null,  JOptionPane.WARNING_MESSAGE);
            }
        }else   {
            JOptionPane.showMessageDialog(this,  "Complete todos los campos",null,  JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_CargarActionPerformed

    private void jBtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtn_VolverActionPerformed

    private void jBtn_BuscarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BuscarGeneroActionPerformed
        Controlador.GestionLibreria.resultadoBusqueda=null;
        Controlador.GestionLibreria.busqueda = 2;
        new Busqueda(this, true).setVisible(true);
        if (Controlador.GestionLibreria.resultadoBusqueda instanceof Genero) {
            genero = (Genero) Controlador.GestionLibreria.resultadoBusqueda;
            jlbl_GeneroSeleccionado.setText(genero.getNombre());            
        }
    }//GEN-LAST:event_jBtn_BuscarGeneroActionPerformed

    private void jBtn_BuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BuscarAutorActionPerformed
        Controlador.GestionLibreria.resultadoBusqueda=null;
        Controlador.GestionLibreria.busqueda = 3;
        new Busqueda(this, true).setVisible(true);
        if (Controlador.GestionLibreria.resultadoBusqueda instanceof Escritor) {
            autor = (Escritor) Controlador.GestionLibreria.resultadoBusqueda;
            jLbl_AutorSeleccionado.setText(autor.getNombres()+" "+autor.getApellidos());
        }
    }//GEN-LAST:event_jBtn_BuscarAutorActionPerformed

    private void jBtn_BuscarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BuscarEditorialActionPerformed
        Controlador.GestionLibreria.resultadoBusqueda=null;
        Controlador.GestionLibreria.busqueda = 4;
        new Busqueda(this, true).setVisible(true);
        if (Controlador.GestionLibreria.resultadoBusqueda instanceof SelloEditorial) {
            sello = (SelloEditorial) Controlador.GestionLibreria.resultadoBusqueda;
            jLbl_EditorialSeleccionada.setText(sello.getNombre());
        }
    }//GEN-LAST:event_jBtn_BuscarEditorialActionPerformed

    private void jTxt_ISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_ISBNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_BuscarAutor;
    private javax.swing.JButton jBtn_BuscarEditorial;
    private javax.swing.JButton jBtn_BuscarGenero;
    private javax.swing.JButton jBtn_Cargar;
    private javax.swing.JButton jBtn_Volver;
    private javax.swing.JLabel jLbl_Autor;
    private javax.swing.JLabel jLbl_AutorSeleccionado;
    private javax.swing.JLabel jLbl_EditorialSeleccionada;
    private javax.swing.JLabel jLbl_Genero;
    private javax.swing.JLabel jLbl_ISBN;
    private javax.swing.JLabel jLbl_NvLibro;
    private javax.swing.JLabel jLbl_Precio;
    private javax.swing.JLabel jLbl_Titulo;
    private javax.swing.JLabel jLnl_Editorial;
    private javax.swing.JPanel jPan_Datos;
    private javax.swing.JPanel jPan_General;
    private javax.swing.JTextField jTxt_ISBN;
    private javax.swing.JTextField jTxt_Precio;
    private javax.swing.JTextField jTxt_Titulo;
    private javax.swing.JLabel jlbl_GeneroSeleccionado;
    // End of variables declaration//GEN-END:variables
    private Genero genero;
    private Escritor autor;
    private SelloEditorial sello;

    private void limpiarDatos() {
        genero=null;
        autor=null;
        sello=null;
        jLbl_AutorSeleccionado.setText("");
        jLbl_EditorialSeleccionada.setText("");
        jlbl_GeneroSeleccionado.setText("");
        jTxt_Precio.setText("");
        jTxt_Titulo.setText("");
        jTxt_ISBN.setText("");
    }
    
}
