/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO.GrupoEditorialDAOImpl;
import Controlador.TxtMayusculas;
import Modelo.GrupoEditorial;
import Modelo.SelloEditorial;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class NuevoGrupoEditorial extends javax.swing.JDialog {

    /**
     * Creates new form NuevoGrupoEditorial
     */
    public NuevoGrupoEditorial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        TxtMayusculas.soloMayus(jTxt_Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPGeneral = new javax.swing.JPanel();
        jP_Datos = new javax.swing.JPanel();
        jLbl_Nombre = new javax.swing.JLabel();
        jTxt_Nombre = new javax.swing.JTextField();
        jLbl_Descuento = new javax.swing.JLabel();
        jTxt_Descuento = new javax.swing.JTextField();
        jLbl_Titulo = new javax.swing.JLabel();
        jBtn_Volver = new javax.swing.JButton();
        jBtn_Cargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(550, 375));
        setMinimumSize(new java.awt.Dimension(550, 375));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(550, 375));
        setResizable(false);

        jPGeneral.setMaximumSize(new java.awt.Dimension(550, 375));
        jPGeneral.setMinimumSize(new java.awt.Dimension(550, 375));
        jPGeneral.setPreferredSize(new java.awt.Dimension(550, 350));

        jP_Datos.setPreferredSize(new java.awt.Dimension(480, 150));

        jLbl_Nombre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Nombre.setText("Nombre:");

        jTxt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_NombreActionPerformed(evt);
            }
        });

        jLbl_Descuento.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLbl_Descuento.setText("Descuento: ");

        jTxt_Descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_DescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_DatosLayout = new javax.swing.GroupLayout(jP_Datos);
        jP_Datos.setLayout(jP_DatosLayout);
        jP_DatosLayout.setHorizontalGroup(
            jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLbl_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jP_DatosLayout.setVerticalGroup(
            jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_DatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_Descuento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLbl_Titulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl_Titulo.setText("Nuevo Grupo Editorial - Proveedor");

        jBtn_Volver.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBtn_Volver.setText("Volver al Menu");
        jBtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VolverActionPerformed(evt);
            }
        });

        jBtn_Cargar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtn_Cargar.setText("Cargar");
        jBtn_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGeneralLayout = new javax.swing.GroupLayout(jPGeneral);
        jPGeneral.setLayout(jPGeneralLayout);
        jPGeneralLayout.setHorizontalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGeneralLayout.createSequentialGroup()
                        .addGap(0, 379, Short.MAX_VALUE)
                        .addComponent(jBtn_Volver)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGeneralLayout.createSequentialGroup()
                        .addComponent(jP_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPGeneralLayout.createSequentialGroup()
                        .addComponent(jLbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        jPGeneralLayout.setVerticalGroup(
            jPGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGeneralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBtn_Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jP_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_NombreActionPerformed

    private void jBtn_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CargarActionPerformed
        if (!jTxt_Nombre.getText().equals("") && !jTxt_Descuento.getText().equals("")) {
            GrupoEditorial nuevoGrupo = new GrupoEditorial(jTxt_Nombre.getText(), Double.parseDouble(jTxt_Descuento.getText()));
            new GrupoEditorialDAOImpl().agregar(nuevoGrupo);
            limpiar();
        }else{
            JOptionPane.showMessageDialog(this, "Complete todos los campos","", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_CargarActionPerformed

    private void jBtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtn_VolverActionPerformed

    private void jTxt_DescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_DescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_DescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoGrupoEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoGrupoEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoGrupoEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoGrupoEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoGrupoEditorial dialog = new NuevoGrupoEditorial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Cargar;
    private javax.swing.JButton jBtn_Volver;
    private javax.swing.JLabel jLbl_Descuento;
    private javax.swing.JLabel jLbl_Nombre;
    private javax.swing.JLabel jLbl_Titulo;
    private javax.swing.JPanel jPGeneral;
    private javax.swing.JPanel jP_Datos;
    private javax.swing.JTextField jTxt_Descuento;
    private javax.swing.JTextField jTxt_Nombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jTxt_Nombre.setText("");
        jTxt_Descuento.setText("");
    }
}
