/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO.SelloEditorialDAOImpl;
import Controlador.TxtMayusculas;
import Modelo.GrupoEditorial;
import Modelo.SelloEditorial;
import javax.swing.JOptionPane;

/**
 *
 * @author Matias
 */
public class NuevoSello extends javax.swing.JFrame {

    /**
     * Creates new form NuevoSello
     */
    public NuevoSello() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        TxtMayusculas.soloMayus(jTxt_Nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPan_General = new javax.swing.JPanel();
        jBtn_Volver = new javax.swing.JButton();
        jBtn_Cargar = new javax.swing.JButton();
        jPan_Datos = new javax.swing.JPanel();
        jLbl_Nombre = new javax.swing.JLabel();
        jTxt_Nombre = new javax.swing.JTextField();
        jLbl_Grupo = new javax.swing.JLabel();
        jLbl_GrupoSeleccionado = new javax.swing.JLabel();
        jBtn_BuscarGrupo = new javax.swing.JButton();
        jLblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 400));
        setMinimumSize(new java.awt.Dimension(550, 400));
        setUndecorated(true);
        setResizable(false);

        jPan_General.setBackground(new java.awt.Color(204, 204, 255));
        jPan_General.setMaximumSize(new java.awt.Dimension(550, 400));
        jPan_General.setMinimumSize(new java.awt.Dimension(550, 400));

        jBtn_Volver.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBtn_Volver.setText("Volver al menu");
        jBtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VolverActionPerformed(evt);
            }
        });

        jBtn_Cargar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jBtn_Cargar.setText("Cargar");
        jBtn_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_CargarActionPerformed(evt);
            }
        });

        jPan_Datos.setBackground(new java.awt.Color(204, 204, 255));

        jLbl_Nombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbl_Nombre.setText("Nombre:");

        jTxt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_NombreActionPerformed(evt);
            }
        });

        jLbl_Grupo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbl_Grupo.setText("Grupo Editorial:");

        jLbl_GrupoSeleccionado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtn_BuscarGrupo.setText("...");
        jBtn_BuscarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_BuscarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPan_DatosLayout = new javax.swing.GroupLayout(jPan_Datos);
        jPan_Datos.setLayout(jPan_DatosLayout);
        jPan_DatosLayout.setHorizontalGroup(
            jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_DatosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbl_Grupo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLbl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPan_DatosLayout.createSequentialGroup()
                        .addComponent(jLbl_GrupoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_BuscarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPan_DatosLayout.setVerticalGroup(
            jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_DatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxt_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLbl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbl_Grupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPan_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLbl_GrupoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_BuscarGrupo)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLblTitulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("Nuevo Sello Editorial");

        javax.swing.GroupLayout jPan_GeneralLayout = new javax.swing.GroupLayout(jPan_General);
        jPan_General.setLayout(jPan_GeneralLayout);
        jPan_GeneralLayout.setHorizontalGroup(
            jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan_GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan_GeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPan_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPan_GeneralLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jBtn_Cargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPan_GeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_Volver)
                .addGap(52, 52, 52))
        );
        jPan_GeneralLayout.setVerticalGroup(
            jPan_GeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPan_GeneralLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jBtn_Volver)
                .addGap(18, 18, 18)
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPan_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtn_Cargar)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPan_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VolverActionPerformed
        this.dispose();

    }//GEN-LAST:event_jBtn_VolverActionPerformed

    private void jTxt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_NombreActionPerformed

    private void jBtn_BuscarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_BuscarGrupoActionPerformed
        Controlador.GestionLibreria.busqueda=1;
        new Busqueda(this,true).setVisible(true);
        if (Controlador.GestionLibreria.resultadoBusqueda instanceof GrupoEditorial) {
            GrupoEditorial grupo= (GrupoEditorial) Controlador.GestionLibreria.resultadoBusqueda;
            jLbl_GrupoSeleccionado.setText(grupo.getNombre());
        }
        
    }//GEN-LAST:event_jBtn_BuscarGrupoActionPerformed

    private void jBtn_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_CargarActionPerformed
        if (!jTxt_Nombre.getText().equals("") && !jLbl_GrupoSeleccionado.getText().equals("")) {
            if(Controlador.GestionLibreria.resultadoBusqueda instanceof GrupoEditorial){
                GrupoEditorial grupoSeleccionado = (GrupoEditorial)Controlador.GestionLibreria.resultadoBusqueda;
                SelloEditorial nuevoSello= new SelloEditorial(jTxt_Nombre.getText(),grupoSeleccionado );
                if (new SelloEditorialDAOImpl().agregar(nuevoSello)) {
                    JOptionPane.showMessageDialog(this, "Sello cargado con exito");
                    limpiar();
                }  else{
                    JOptionPane.showMessageDialog(this, "Fallo al cargar",null,  JOptionPane.WARNING_MESSAGE) ;
                }              
            }else   {
                JOptionPane.showMessageDialog(this, "Seleccione un Grupo Editorial",null,  JOptionPane.WARNING_MESSAGE);
            }         
        }else{
            JOptionPane.showMessageDialog(this,  "Complete todos los campos",null,  JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBtn_CargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoSello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoSello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoSello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoSello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoSello().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_BuscarGrupo;
    private javax.swing.JButton jBtn_Cargar;
    private javax.swing.JButton jBtn_Volver;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLbl_Grupo;
    private javax.swing.JLabel jLbl_GrupoSeleccionado;
    private javax.swing.JLabel jLbl_Nombre;
    private javax.swing.JPanel jPan_Datos;
    private javax.swing.JPanel jPan_General;
    private javax.swing.JTextField jTxt_Nombre;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jLbl_GrupoSeleccionado.setText("");
        jTxt_Nombre.setText("");
    }
}
